version: '3.8'
services:
    web:
        build: ./app

        stdin_open: true
        tty: true
        ports: 
            - "8080:8080"
        volumes:
            - "./app:/app"
        environment: 
            - CHOKIDAR_USEPOLLING=true


    server:
        build: ./node
        
        ports: 
            - "3000:3000"
        volumes:
            - upload:/node/server/public/upload/
            - ./node/server/public/upload/:/usr/src/app/node/server/public/upload/
            - profiles:/node/server/public/profiles/
            - ./node/server/public/profiles/:/usr/src/app/node/server/public/profiles/
        links:
            - server-database         
    
  
    server-database:
        image: mongo
        container_name: "mongo"
        restart: always
        volumes:
            - './dockervolume/mongodb:/data/db'
        ports:
            - 27017:27017
    
volumes:
    upload:
    profiles:
    
        